example_makefiles/makefile.inc.Linux

This is my current configuration for MKL on Ubuntu.
I also corrected the `BLASLDFLAGS=-DFINTEGER=long` line (it should be `BLASCFLAGS`).

Changing a few settings for MKL on Ubuntu

---

example_makefiles/makefile.inc.Linux

swiggfaiss_wrap.cxx already include <numpy/arrayobject.h>, if compiled with -I/usr/lib64/python2.7/site-packages/numpy/core/include/numpy, file will be searched at /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/numpy/arrayobject.h and will not be found.

Removed numpy directory from include directory

---

gpu/utils/StaticUtils.h

The bit shift was done as int and not as current type (size_t for example), thus the computed next highest power of 2 was wrong on large numbers.
It seems to solve issue #108 (or at least it does not fail right aways, computations are not finished yet)

correct utils::nextHighestPowerOf2

---

gpu/utils/DeviceDefs.cuh

Add support for Nvidia GPUs with CUDA compute capability 6.1: GeForce Titan X (Pascal)/Xp/10*0, Quadro P*000, Tesla P4*, ...

add support for Nvidia GPUs with CUDA compute capability 6.1

---

example_makefiles/makefile.inc.Mac.brew

Removing old flag `-Dnullptr=NULL` that causes issues with installation on osx with brew.

Fix makefile.inc.Mac.brew

---

INSTALL.md

I'm submitting this PR to update the INSTALL.md documentation with a few corrections from running into issues myself.  Also a slight change to the `PYTHONPATH` modification
1. The `sift1M` files should be downloaded to the root of the repository as this is where the respective tests are run.  If it is installed anywhere else, the tests fail.
2. The setting of the `PYTHONPATH` would clear out any existing locations set previous to this script running, for the duration of the shell session.  I've made an adjustment to make it more temporary.
3. The `demo_auto_tune.py` file is in `tests` not `python`

updates to INSTALL.md

---

tutorial/cpp/4-GPU.cpp
tutorial/cpp/5-Multiple-GPUs.cpp
tutorial/cpp/Makefile
tutorial/python/1-Flat.py
tutorial/python/2-IVFFlat.py
tutorial/python/3-IVFPQ.py
tutorial/python/4-GPU.py
tutorial/python/5-Multiple-GPUs.py

[WIP] Update tutorial

---

tests/test_build_blocks.py
tests/test_index_composite.py

I'm building conda packages for faiss and encountered test failure with py3. 
Making tests compatible with py3.

Make tests compatible with py3

---

INSTALL.md
README.md

FAISS conda packages has been uploaded to pytorch anaconda channel here. https://anaconda.org/pytorch/repo.
Updating the README to include this installation method.

update Readme to include conda install info

---

IndexPQ.cpp
IndexPQ.h

Hi,
I found remove_ids was not implemented in IndexPQ when playing with faiss and made a patch of it like what was done in IndexFlat, hope you can take a review.

Implement remove_ids in IndexPQ

---

c_api/IndexFlat_c.cpp
c_api/IndexFlat_c.h
c_api/IndexIVFFlat_c.cpp
c_api/IndexIVFFlat_c.h
c_api/IndexIVF_c.cpp
c_api/IndexIVF_c.h
c_api/IndexLSH_c.cpp
c_api/IndexLSH_c.h
c_api/Makefile
c_api/MetaIndexes_c.cpp
c_api/MetaIndexes_c.h
c_api/example_c.c
c_api/faiss_c.h
c_api/index_io_c.cpp
c_api/index_io_c.h
c_api/macros_impl.h

This PR extends the C API with some some functions and types for accessing features in the library which may be useful in bindings. It is composed of 3 major contributions (feel free to let me know if you would like separate pull requests instead):
- Bridged `IndexLSH` to the C interface, which to my understanding isn't accessible through the index factory.
- Added most of "index_io.h" to the C header file "index_io_c.h", so as to enable saving and loading indices to/from disk. To serve as an example, "example_c.c" was extended to save the index in the end.
- Added most of "MetaIndexes.h" to the C counterpart "MetaIndexes_c.h", thus allowing users to create index ID maps and index shards.
Although this is not yet fully tested, generating the low-level Rust bindings containing these …

[C API] Additional API coverage: IndexLSH, I/O, meta-indexes

---

CMakeLists.txt

CMakeLists.txt, so we can install the libs and headers with make
install.

- Add install target for the faiss library and headers to the

---

c_api/Makefile
c_api/gpu/Makefile

I just noticed a tiny issue in the previous extension to the C API, which this PR corrects.
The new object files from #425 were not being included in the GPU shared object because `c_api/gpu/Makefile` was keeping its own replicated list of object files.
I adjusted the libgpufaiss_c.so building process so that it fetches the complete archive file built from c_api/Makefile, thus potentially avoiding these mistakes in the future.
- Change `libfaiss_c.a` and `libgpufaiss_c.a` targets to only include the C interface's wrapper implementations
- Include `libfaiss_c.a` target on `c_api`'s `make all`
- Build `libgpufaiss_c.so` with `libfaiss_c.a` instead of the "*_c.o" object files in the parent directory

[C API] Fix libgpufaiss_c with extended API

---

faiss.py

I noticed that the `assign` method in the Python interface was not adapted to a high level API, like the other operations (`add`, `search`, `reconstruct`, ...). Steps to reproduce the issue:
```python
import numpy as np
import faiss
index = faiss.index_factory(2, "Flat")
index.add(np.array([[1, 2], [3, 4]], dtype=np.float32))
labels = index.assign(np.array([[0, 0]], dtype=np.float32), 1)
```
```txt
TypeError: assign() missing 1 required positional argument: 'labels'
```
With these changes, the code above now works as expected. One could indeed use `search` instead, but I did not need to fetch the distances in my use case.

Support for index.assign in Python

---

c_api/Makefile
c_api/example_c.c
c_api/gpu/Makefile
c_api/gpu/example_gpu_c.c

Here are the necessary adjustments to the building process of the C API after #466. It is mostly a change of environment variable flags. I also removed the use of `inline` in the respective example files, which was not needed and could bring compilation issues.

Make c_api compatible with configure'd makefile

---

Makefile

Fix linking order for misc/test_blas in Makefile.

---

c_api/Makefile
c_api/gpu/Makefile

Turns out that the Makefiles in the C interface also had the library linking order issue as the one in #487, and solved in #489. It seemed to work locally, but it failed when trying to get Travis to compile the Rust bindings.

[C API] Rearrange lib linking order

---

INSTALL.md

Add libgcc as runtime dependency since we use gcc in conda to compile and it links libstdc++ and libgomp.

update conda install info for release 1.3.0

---

c_api/Index_c.h
c_api/gpu/GpuAutoTune_c.cpp
c_api/gpu/GpuAutoTune_c.h
c_api/gpu/GpuClonerOptions_c.cpp
c_api/gpu/GpuClonerOptions_c.h

This PR provides access to the `cpu_to_gpu_multiple` function and other related data types. A few minor tweaks to the C API are included as well:
- fix doc comment in `FaissGpuClonerOptions` constructor
- include `stddef.h` instead of `stdio.h` in the `Index_c.h` header file
A small check for validation would be much appreciated: Is it safe to assume that the arguments `resources` and `devices` are required to have the same length?

[C API] Multi-GPU functions

---

gpu/Makefile

This trivial change installs both the FAISS non-gpu and gpu library artifacts into the same output location so that downstream projects can build against them.

For #669. Adding install target to gpu Makefile

---

demos/demo_ondisk_ivf.py

When data is being added to each index block, it needs to explicitly identify ids. Otherwise, the ids are automatically assumed to be the index of each individual data block, so every block has the same ids (in the range of 0 to 250,000).

ondisk demo bug fix: data needs to be added with ids

---

gpu/utils/Tensor.cuh

The GPU compilation fails with g++ 8.3.1 and cuda 10.1
With this proposed fix the compilation works locally
Contributes to #751

fix: gpu compilation with cuda 10.1

---

tutorial/cpp/Makefile

Since faiss GPU library is not separated with CPU library anymore, the makefile for tutorial need be updated. 
~~`$(CUDACFLAGS)` may not be generated by ./configure, however,  you can add `CUDACFLAGS   = -I $(CUDA_ROOT)/include` in the makefile.inc or use modifed makefile.inc from example_makefiles accordingly.~~

Update cpp tutorial makefile for GPU part

---

tutorial/cpp/Makefile

when using custom cuda,
```
configure --with-cuda /path/to/cuda
```
CPPFLAGS will contains cuda include path
Add CPPFLAGS in tutorial Makefile.

tutorial build add CPPFLAGS which contains cuda include path

---

gpu/utils/Tensor.cuh

#771 was not sufficient as the latest platform in my case.
I checked the compilation works with this PR.
```
$ make
...
impl/../utils/Tensor.cuh(362): error: type name is not allowed
impl/../utils/Tensor.cuh(362): error: expected an expression
```
```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
```
```
$ g++ --version
g++ (Ubuntu 8.3.0-6ubuntu1~18.04.1) 8.3.0
```
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Fri_Feb__8_19:08:17_PST_2019
Cuda compilation tools, release 10.1, V10.1.105
```

Fix gpu compilation with cuda 10.1 related to #751

---

c_api/AuxIndexStructures_c.cpp
c_api/AuxIndexStructures_c.h
c_api/IndexIVFFlat_c.cpp
c_api/IndexIVFFlat_c.h
c_api/IndexIVF_c.cpp
c_api/IndexIVF_c.h
c_api/Index_c.cpp
c_api/Index_c.h
c_api/Makefile
c_api/MetaIndexes_c.cpp
c_api/MetaIndexes_c.h
c_api/example_c.c
c_api/faiss_c.h
c_api/gpu/Makefile
c_api/gpu/example_gpu_c.c

This is a set of changes to adapt the C API to the latest major updates. Quick summary:
- Update Makefiles in c_api to include the relevant flags from makefile.inc
- Type changes: use `idx_t` or `size_t` where appropriate instead of `long`
- Remove a redundant declaration of `FaissIndexIVF`

[C API] June 2019 update

---

gpu/GpuIndexIVFScalarQuantizer.cu

In  gpu/GpuIndexIVFScalarQuantizer.cu copyTo function. Index->code_size isn't set. And the code_size will be used in creating new invertedlist, which will lead to error.
Solution:
code_size is stored in scalar_quantizer, just assign it to index->code_size.

Fix GPUSQ copyto bug

---

gpu/GpuIndexIVFScalarQuantizer.cu

nprobe = nprobe; won't set object member: nprobe.

Fix GpuIndexIVF::setNumProbes bug

---

impl/ScalarQuantizer.cpp

The -mf16c (i.e. packed-half conversion) instructions weren't added until the
Ivy Bridge CPU generation (https://en.wikipedia.org/wiki/F16C#CPUs_with_F16C).
Therefore, code dependent on those intrinsics must be conditioned on __F16C__ -
not __AVX__.
Without this patch, the code will not build with -mavx and not also -mf16c or -march=haswell (or later).  After patching, it builds with -mavx and still enables AVX in pure-AVX1 codepaths, while also enabling f16c instructions when an appropriate -m flag is specified.

Fixes to enable building with -mavx, for Sandybridge CPUs.

---

python/faiss.py

`print()` has no control over how messages are displayed. Use `logging` module instead.

Replace print with logging

---

c_api/IndexPreTransform_c.cpp
c_api/IndexPreTransform_c.h
c_api/Makefile

I work with a index built by factory `"PCAR4,IVF4050,SQ8"`
The feature relying this faiss index need to use the `faiss_Index_reconstruct` function.
`faiss_IndexIVF_make_direct_map` need to be called at first, against the underlying IVF casted index.
To retrieve the the IVF underlying casted index, `faiss_IndexIVF_cast` argument must be the underlying index of the pretransform index
```python
import numpy as np
d = 12                           # dimension
nb = 100000                      # database size
nq = 10000                       # nb of queries
...
import faiss
conf = "PCAR4,IVF4050,SQ8"
index = faiss.index_factory(d, conf)
index.train(xb[:4050])
index.add(xb)
index_ivf = faiss.downcast_index(index.index)
print(index) #<faiss.swigfaiss_avx2.IndexPreTransform; proxy of <Swig Object …
```

[ C api ] Indexpretransform get underlying index 

---

python/faiss.py

One can pass parameter gpus to index_cpu_to_gpus_list to use only selected GPU's, i.e. if we pass gpus=[1, 3, 4], we will use 1-st, 3-rd and 4-th graphical cards

Add support to use selected GPUs by id

---

c_api/Clustering_c.cpp
c_api/Clustering_c.h

fix https://github.com/facebookresearch/faiss/issues/1139
based on https://github.com/facebookresearch/faiss/issues/1139#issuecomment-598246480

C API : ClusteringIterationStats integration

---

python/faiss.py

numpy's CPU info dictionary does not have a 'flags' field on some
CPU architectures (such as ppc64le). Tolerate absence of 'flags'
when checking for instruction set to allow faiss to continue in
non-AVX2 mode on those architectures.

Improve CPU architecture tolerance

---

gpu/test/demo_ivfpq_indexing_gpu.cpp

Fix the following compilation error (fix #1191)
```c
demo_ivfpq_indexing_gpu.cpp:88:36: error: ‘index_gpu_to_cpu’ is not a member of ‘faiss::gpu’
faiss::Index * cpu_index = faiss::gpu::index_gpu_to_cpu (&index);
```

Fix demo_ivfpq_indexing_gpu compilation error

---

c_api/AutoTune_c.h

ParameterSpace destructor implementation exists but declaration in header file is missing
https://github.com/facebookresearch/faiss/blob/v1.6.3/c_api/AutoTune_c.cpp#L37
it ends up in user code with error
```
faiss/writer/index.go:65:9: could not determine kind of name for C.faiss_ParameterSpace_free
```
the fix resolve this issue

fix free parameterspace

---

c_api/example_c.c
c_api/gpu/GpuAutoTune_c.cpp
c_api/gpu/GpuClonerOptions_c.cpp
c_api/gpu/GpuIndex_c.cpp
c_api/gpu/GpuResources_c.cpp
c_api/gpu/Makefile
c_api/gpu/StandardGpuResources_c.cpp
c_api/gpu/example_gpu_c.c

The changes in the building process of Faiss v1.5.1 affected the C API building process, which currently still relies on separate libfaiss and libgpufaiss. This was probably overlooked due to the lack of CUDA in CI.
I would be interested in improving the makefiles for the C API eventually, but for now this PR will make building the full C library work again.

[C API] Fix GPU library build process

---

python/faiss.py

Fixes typos in `faiss.ResultHeap` that lead to a crash in the attempt of using it.

python: fix faiss.ResultHeap

---

index.rst

Following the move from `master` to `main`, the CI/License badges on
the front page of faiss.ai got stale.

Fix badges on faiss.ai
