facebookresearch/faiss

example_makefiles/makefile.inc.Linux

To resolve the [#issues29](https://github.com/facebookresearch/faiss/issues/29), just add quotation marks for multiple BLASLDFLAGS values in example_makefiles/the makefile.inc.Linux

quote the multiple BLASLDFLAGS values

---

python/demo_ivfpq.py

The rootdir in the distribution seems specific to the creators.  I just made the rootdir for the fvecs be the suggested directory (sift1M) from the installation guide.

Changed rootdir

---

INSTALL.md

make INSTALL a proper markdown file

---

example_makefiles/makefile.inc.Linux

It took me quite some time to get around this error -- it might save others time.

Add LD_PRELOAD update to MKL compile instructions

---

tests/test_build_blocks.py

tested with python 3.6 and 2.7

fix test syntax

---

INSTALL.md

Add missing cd command for cmake bulid

---

Dockerfile

* Updated the build steps to reflect what is in the current INSTALL.md after #347.
* Updated PYTHONPATH to include /opt/faiss directory where `_swigfaiss.so` and `_swigfiass_gpu.so` are located.

updating dockerfile after PR #347 (sync w/ FB) 

---

tutorial/cpp/2-IVFFlat.cpp
tutorial/cpp/Makefile

Hello,
It seems that the cpp tutorial is kind of outdated, so that I make a small patch to fix it.

Fix compile error in cpp tutorial

---

INSTALL.md

Packages have been uploaded to pytorch channel. Updating the INSTALL.md to include support for more platform & CUDA versions. 
This also resolves the dependency ambiguity we had in #371 .

update conda install info

---

Makefile

+ Add `installdirs` target ;
+ add `install` target ;
+ add `uninstall` target.
All targets support customization via `DESTDIR` and `PREFIX`.

Add (un)install Makefile targets for CPU version.

---

MetaIndexes.cpp

clear id_map after index reset

Update IndexIDMap reset

---

Dockerfile

Changes done for the issue #710

Upgrading pip in the Docker Container (#710)

---

acinclude/ax_check_cpu.m4
configure
configure.ac
makefile.inc.in
utils.cpp

Make library compile and run on arm64 8.2 (Nvidia Xavier arm+CUDA)
`configure` is regenerated

Improve arm64 support.

---

demos/demo_ivfpq_indexing.cpp

Fix ivfpq demo.

---

Makefile

Make Makefile bourne shell compliant

---

HNSW.cpp

Fix HNSW.fill_with_random_links

---

index_io.cpp

Fix unable to read untrained index

---

gpu/test/Makefile

Fix Makefile in gpu/test

---

benchs/distributed_ondisk/README.md
benchs/distributed_ondisk/combined_index.py
benchs/distributed_ondisk/distributed_kmeans.py
benchs/distributed_ondisk/distributed_query_demo.py
benchs/distributed_ondisk/make_index_vslice.py
benchs/distributed_ondisk/make_trained_index.py
benchs/distributed_ondisk/merge_to_ondisk.py
benchs/distributed_ondisk/rpc.py
benchs/distributed_ondisk/run_on_cluster.bash
benchs/distributed_ondisk/search_server.py

This is the code corresponding to the wiki on how to index 1T vectors.

Ondisk distributed index implementation

---

IndexFlat.h

Nothing much here except spelling found while reading the code.

Fix spelling error

---

c_api/Clustering_c.h

Fix typo in Clustering_c.h

---

c_api/IndexIVF_c.cpp
c_api/IndexIVF_c.h

I would like to be able to get invlists from c_api

c_api: faiss_IndexIVF_invlists_get_ids function

---

Makefile

Add `.cuh` files to install include dir ,then users can use more APIs and make CUDA testing.

Add .cuh files to install include dir. 

---

AutoTune.h

Correct a spelling mistake

---

tutorial/cpp/1-Flat.cpp
tutorial/cpp/2-IVFFlat.cpp
tutorial/cpp/3-IVFPQ.cpp
tutorial/cpp/4-GPU.cpp

There are leftover longs in the tutorial codes.
long is 32 bit on mac (and on windows), so convert this to idx_t.

fix datatypes for mac

---

docs/_sources/index.rst.txt
docs/index.html
index.rst

Our mission at [Meta Open Source](https://opensource.facebook.com/) is to empower communities through open source, and we believe that it means building a welcoming and safe environment for all. As a part of this work, we are adding this banner in support for Ukraine during this crisis.

docs: add GH button in support of Ukraine 

---

conf.py
index.rst

also replaces circle-ci badge with github actions badge

[Fixes #3500] moves terms of use and privacy policy to faiss.ai
